# Real madrid 25-26 vs Real madrid 23-24

In [52]:
import pandas as pd

In [53]:
team_25_26 = pd.read_csv("RM2526/team-players.csv",sep=";")
situacion_25_26 = pd.read_csv("RM2526/team-statistics.csv",sep=";")
formacion_25_26 = pd.read_csv("RM2526/team-statistics (1).csv",sep=";")
game_estate_25_26 = pd.read_csv("RM2526/team-statistics (2).csv",sep=";")
timing_25_26 = pd.read_csv("RM2526/team-statistics (3).csv",sep=";")
shot_zones_25_26 = pd.read_csv("RM2526/team-statistics (4).csv",sep=";")
attack_speed_25_26 = pd.read_csv("RM2526/team-statistics (5).csv",sep=";")
result_25_26 = pd.read_csv("RM2526/team-statistics (6).csv",sep=";")

In [93]:
team_23_24 = pd.read_csv("RM2324/team-players (1).csv",sep=";")
situacion_23_24 = pd.read_csv("RM2324/team-statistics (7).csv",sep=";")
formacion_23_24 = pd.read_csv("RM2324/team-statistics (8).csv",sep=";")
game_estate_23_24 = pd.read_csv("RM2324/team-statistics (9).csv",sep=";")
timing_23_24 = pd.read_csv("RM2324/team-statistics (10).csv",sep=";")
shot_zones_23_24 = pd.read_csv("RM2324/team-statistics (11).csv",sep=";")
attack_speed_23_24 = pd.read_csv("RM2324/team-statistics (12).csv",sep=";")
result_23_24 = pd.read_csv("RM2324/team-statistics (13).csv",sep=";")
team_24_25 = pd.read_csv("team-players (2).csv",sep=";")

In [94]:
formacion_25_26.rename(columns={"statistic": "formacion"}, inplace=True)
situacion_25_26.rename(columns={"statistic": "situacion"}, inplace=True)
game_estate_25_26.rename(columns={"statistic": "game_estate"}, inplace=True)
timing_25_26.rename(columns={"statistic": "timing"}, inplace=True)
shot_zones_25_26.rename(columns={"statistic": "shot_zones"}, inplace=True)
attack_speed_25_26.rename(columns={"statistic": "attack_speed"}, inplace=True)
result_25_26.rename(columns={"statistic": "result"}, inplace=True)
formacion_23_24.rename(columns={"statistic": "formacion"}, inplace=True)
situacion_23_24.rename(columns={"statistic": "situacion"}, inplace=True)
game_estate_23_24.rename(columns={"statistic": "game_estate"}, inplace=True)
timing_23_24.rename(columns={"statistic": "timing"}, inplace=True)
shot_zones_23_24.rename(columns={"statistic": "shot_zones"}, inplace=True)
attack_speed_23_24.rename(columns={"statistic": "attack_speed"}, inplace=True)
result_23_24.rename(columns={"statistic": "result"}, inplace=True)

In [104]:
df_2526=[team_25_26,formacion_25_26,situacion_25_26,game_estate_25_26,timing_25_26,shot_zones_25_26,attack_speed_25_26,result_25_26]
df_2324=[team_23_24,formacion_23_24,situacion_23_24,game_estate_23_24,timing_23_24,shot_zones_23_24,attack_speed_23_24,result_23_24]
for df in df_2526:
    df["season"] = "25-26"
for df in df_2324:
    df["season"] = "23-24"
team_24_25["season"] = "24-25"

In [105]:
formacion=pd.concat([formacion_25_26, formacion_23_24], ignore_index=True)
situacion=pd.concat([situacion_25_26, situacion_23_24], ignore_index=True)
game_estate=pd.concat([game_estate_25_26, game_estate_23_24], ignore_index=True)
timing=pd.concat([timing_25_26, timing_23_24], ignore_index=True)
shot_zones=pd.concat([shot_zones_25_26, shot_zones_23_24], ignore_index=True)
attack_speed=pd.concat([attack_speed_25_26, attack_speed_23_24], ignore_index=True)
result=pd.concat([result_25_26, result_23_24], ignore_index=True)
team=pd.concat([team_25_26, team_23_24, team_24_25], ignore_index=True)

In [98]:
dfs= [formacion, situacion, game_estate, timing, shot_zones, attack_speed, result, team]
for df in dfs:
    df.drop(columns=['number'], inplace=True)

# FORMACION

In [59]:

formacion.head(20).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15
formacion,4-4-2,4-2-3-1,4-3-3,4-1-4-1,3-4-2-1,3-4-1-2,4-4-1-1,4-2-2-2,4-3-1-2,4-1-2-1-2,4-2-3-1,4-3-3,4-4-2,4-2-2-2,4-1-3-2,4-4-1-1
min,1320,1025,615,126,83,67,61,26,1450,560,534,420,292,257,96,14
shots,218,200,120,32,22,13,7,8,271,87,67,70,54,35,13,2
goals,29,18,14,3,4,0,1,1,34,9,10,14,13,5,2,0
shots_against,157,114,52,15,11,8,19,2,162,76,62,32,17,25,14,3
goals_against,16,12,1,1,1,1,1,0,8,7,6,2,2,0,1,0
xG,25.86,23.16,16.02,4.65,3.6,1.79,0.94,1.0,39.55,11.06,8.92,9.56,9.47,4.65,0.96,0.43
xGA,19.12,11.17,4.93,1.12,1.77,1.19,3.03,0.56,14.92,10.36,6.04,3.37,2.66,2.18,1.33,0.15
xG_diff,6.73,11.99,11.09,3.53,1.84,0.6,-2.1,0.44,24.63,0.7,2.88,6.19,6.82,2.48,-0.37,0.28
xG90,1.76,2.03,2.34,3.32,3.91,2.4,1.38,3.48,2.45,1.78,1.5,2.05,2.92,1.63,0.9,2.78
xGA90,1.3,0.98,0.72,0.8,1.91,1.6,4.47,1.95,0.93,1.66,1.02,0.72,0.82,0.76,1.25,0.95
season,25-26,25-26,25-26,25-26,25-26,25-26,25-26,25-26,23-24,23-24,23-24,23-24,23-24,23-24,23-24,23-24

In [60]:
formacion=formacion[formacion["min"]>200]

In [61]:
formacion

,formacion,min,shots,goals,shots_against,goals_against,xG,xGA,xG_diff,xG90,xGA90,season
0,4-4-2,1320,218,29,157,16,25.86,19.12,6.73,1.76,1.30,25-26
1,4-2-3-1,1025,200,18,114,12,23.16,11.17,11.99,2.03,0.98,25-26
2,4-3-3,615,120,14,52,1,16.02,4.93,11.09,2.34,0.72,25-26
8,4-3-1-2,1450,271,34,162,8,39.55,14.92,24.63,2.45,0.93,23-24
9,4-1-2-1-2,560,87,9,76,7,11.06,10.36,0.70,1.78,1.66,23-24
10,4-2-3-1,534,67,10,62,6,8.92,6.04,2.88,1.50,1.02,23-24
11,4-3-3,420,70,14,32,2,9.56,3.37,6.19,2.05,0.72,23-24
12,4-4-2,292,54,13,17,2,9.47,2.66,6.82,2.92,0.82,23-24
13,4-2-2-2,257,35,5,25,0,4.65,2.18,2.48,1.63,0.76,23-24

# Situacion

In [62]:
situacion.sort_values(by="situacion", ascending=False)

,situacion,shots,goals,shots_against,goals_against,xG,xGA,xG_diff,xGperSh,xGAperSh,season
2,Set piece,42,6,23,1,6.20,4.74,1.46,0.15,0.21,25-26
8,Set piece,22,1,23,0,2.43,2.82,-0.39,0.11,0.12,23-24
4,Penalty,14,12,4,4,10.41,2.97,7.43,0.74,0.74,25-26
9,Penalty,5,2,1,1,3.72,0.74,2.97,0.74,0.74,23-24
0,Open play,442,45,293,25,48.13,30.78,17.35,0.11,0.11,25-26
5,Open play,464,74,296,23,66.85,31.78,35.06,0.14,0.11,23-24
1,From corner,105,7,47,1,10.24,3.59,6.65,0.10,0.08,25-26
6,From corner,83,10,64,2,9.95,5.26,4.69,0.12,0.08,23-24
3,Direct Freekick,17,0,11,2,2.06,0.83,1.22,0.12,0.08,25-26
7,Direct Freekick,25,0,7,0,1.65,0.39,1.27,0.07,0.06,23-24

# GAME ESTATE

In [63]:
game_estate.sort_values(by="game_estate", ascending=False)

,game_estate,min,shots,goals,shots_against,goals_against,xG,xGA,xG_diff,xG90,xGA90,season
2,Goal diff > +1,450,93,11,74,6,14.89,9.15,5.74,2.98,1.83,25-26
7,Goal diff > +1,634,129,20,91,6,23.12,7.32,15.80,3.28,1.04,23-24
4,Goal diff < -1,98,8,0,10,1,0.60,1.51,-0.91,0.55,1.38,25-26
9,Goal diff < -1,99,23,3,10,0,1.76,0.68,1.08,1.60,0.62,23-24
0,Goal diff 0,1637,293,33,152,14,32.13,16.66,15.47,1.77,0.92,25-26
5,Goal diff 0,1759,250,34,175,11,31.65,21.40,10.25,1.62,1.10,23-24
3,Goal diff -1,272,61,8,18,3,8.48,3.11,5.37,2.80,1.03,25-26
8,Goal diff -1,342,66,10,32,4,8.69,3.47,5.22,2.29,0.91,23-24
1,Goal diff +1,866,165,18,124,9,20.93,12.48,8.45,2.17,1.30,25-26
6,Goal diff +1,789,131,20,83,5,19.39,8.13,11.26,2.21,0.93,23-24

In [64]:
game_estate["estado_juego"] = game_estate["game_estate"].apply(
    lambda x:
    "Ganando" if "+" in x
    else "Empatando" if "0" in x
    else "Perdiendo"
)

In [65]:
game_estate.groupby(["estado_juego","season"]).sum("min")

                      min  shots  goals  shots_against  goals_against     xG  \
estado_juego season
Empatando    23-24   1759    250     34            175             11  31.65
             25-26   1637    293     33            152             14  32.13
Ganando      23-24   1423    260     40            174             11  42.51
             25-26   1316    258     29            198             15  35.82
Perdiendo    23-24    441     89     13             42              4  10.45
             25-26    370     69      8             28              4   9.08

                       xGA  xG_diff  xG90  xGA90
estado_juego season
Empatando    23-24   21.40    10.25  1.62   1.10
             25-26   16.66    15.47  1.77   0.92
Ganando      23-24   15.45    27.06  5.49   1.97
             25-26   21.63    14.19  5.15   3.13
Perdiendo    23-24    4.15     6.30  3.89   1.53
             25-26    4.62     4.46  3.35   2.41

# TIMING

In [66]:
timing.sort_values(by="timing", ascending=False)

,timing,shots,goals,shots_against,goals_against,xG,xGA,xG_diff,xGperSh,xGAperSh,season
5,76+,131,16,88,8,18.59,9.20,9.40,0.14,0.10,25-26
11,76+,113,16,95,3,19.40,6.79,12.61,0.17,0.07,23-24
4,61-75,92,11,74,6,12.02,8.07,3.94,0.13,0.11,25-26
10,61-75,112,17,45,3,17.31,5.17,12.15,0.15,0.11,23-24
3,46-60,107,14,69,7,13.52,10.01,3.51,0.13,0.15,25-26
9,46-60,113,22,75,5,15.50,8.76,6.74,0.14,0.12,23-24
2,31-45,107,12,59,6,12.91,6.86,6.05,0.12,0.12,25-26
8,31-45,103,9,64,3,10.13,5.67,4.46,0.10,0.09,23-24
1,16-30,106,12,42,4,14.17,4.54,9.64,0.13,0.11,25-26
7,16-30,80,13,55,4,12.52,5.17,7.35,0.16,0.09,23-24
0,1-15,77,5,46,2,5.80,4.22,1.58,0.08,0.09,25-26
6,1-15,78,10,57,8,9.74,9.44,0.30,0.12,0.17,23-24

# SHOT ZONES

In [72]:
shot_zones.sort_values(by="shot_zones", ascending=False)

,shot_zones,shots,goals,shots_against,goals_against,xG,xGA,xG_diff,xGperSh,xGAperSh,season
3,Six-yard box,38,10,22,6,13.93,8.44,5.49,0.37,0.38,25-26
7,Six-yard box,39,14,24,5,18.28,9.57,8.71,0.47,0.40,23-24
2,Penalty area,357,46,214,19,54.35,28.70,25.65,0.15,0.13,25-26
6,Penalty area,343,62,216,18,56.90,25.84,31.06,0.17,0.12,23-24
0,Own goals,0,0,1,1,0.00,1.00,-1.00,0.00,1.00,25-26
4,Own goals,2,2,1,1,2.00,1.00,1.00,1.00,1.00,23-24
1,Out of box,225,14,141,7,8.75,4.77,3.98,0.04,0.03,25-26
5,Out of box,215,9,150,2,7.42,4.59,2.83,0.03,0.03,23-24

# Attack speed

In [70]:
attack_speed["attack_speed"] = attack_speed["attack_speed"].replace(
    "Standard",
    "Normal"
)

In [73]:
attack_speed_grouped = attack_speed.groupby(["season", "attack_speed"])[[
    "shots",
    "goals",
    "shots_against",
    "goals_against",
    "xG_diff"
]].sum()

display(attack_speed_grouped)

                     shots  goals  shots_against  goals_against  xG_diff
season attack_speed
23-24  Fast             26      5             24              4     1.05
       Normal          526     77            340             19    42.50
       Slow             47      5             27              3     0.05
25-26  Fast             35      6             22              3     2.26
       Normal          523     60            325             28    30.48
       Slow             62      4             31              2     1.38

In [76]:
attack_speed_grouped.sort_values(by="attack_speed", ascending=False)

                     shots  goals  shots_against  goals_against  xG_diff
season attack_speed
23-24  Slow             47      5             27              3     0.05
25-26  Slow             62      4             31              2     1.38
23-24  Normal          526     77            340             19    42.50
25-26  Normal          523     60            325             28    30.48
23-24  Fast             26      5             24              4     1.05
25-26  Fast             35      6             22              3     2.26

# ressult

In [78]:
result.sort_values(by="result", ascending=False)

,result,shots,goals,shots_against,goals_against,xG,xGA,xG_diff,xGperSh,xGAperSh,season
4,Shot on post,11,0,10,0,2.10,1.02,1.07,0.19,0.10,25-26
9,Shot on post,16,0,9,0,3.71,1.78,1.94,0.23,0.20,23-24
1,Saved shot,162,0,78,0,20.25,10.28,9.97,0.12,0.13,25-26
6,Saved shot,161,0,92,0,23.20,10.57,12.63,0.14,0.11,23-24
0,Missed shot,217,0,146,0,18.73,11.90,6.83,0.09,0.08,25-26
5,Missed shot,182,0,155,0,15.61,12.49,3.11,0.09,0.08,23-24
3,Goal,70,70,33,33,24.65,12.93,11.72,0.35,0.39,25-26
8,Goal,87,87,26,26,31.04,10.59,20.46,0.36,0.41,23-24
2,Blocked shot,160,0,111,0,11.30,6.77,4.53,0.07,0.06,25-26
7,Blocked shot,153,0,109,0,11.04,5.57,5.46,0.07,0.05,23-24

# team

In [108]:
team["linea"] = team["position"].apply(
    lambda x: "Ataque" if "F" in x
    else "Medio" if "M" in x
    else "Portero" if "GK" in x
    else "Defensa"
)

In [109]:
team.sort_values(by="linea", ascending=False)

,number,player,position,apps,min,goals,assists,sp90m,kp90,xG,xA,xG90,xA90,season,linea
48,16,Thibaut Courtois,GK,4,336,0,0,0.00,0.27,0.00,0.18,0.00,0.05,23-24,Portero
83,24,Francisco González,GK,1,90,0,0,0.00,0.00,0.00,0.00,0.00,0.00,24-25,Portero
23,24,Andriy Lunin,GK,6,540,0,0,0.00,0.00,0.00,0.00,0.00,0.00,25-26,Portero
17,18,Thibaut Courtois,GK,29,2610,0,0,0.00,0.00,0.00,0.00,0.00,0.00,25-26,Portero
81,22,Andriy Lunin,GK,7,630,0,1,0.00,0.14,0.00,0.92,0.00,0.13,24-25,Portero
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
61,2,Vinícius Júnior,F M,30,2267,11,8,3.22,2.30,12.78,8.64,0.51,0.34,24-25,Ataque
34,2,Vinícius Júnior,F M,26,1902,15,5,3.69,1.47,16.00,4.43,0.76,0.21,23-24,Ataque
33,1,Jude Bellingham,F M,28,2351,19,6,2.41,1.84,12.97,5.89,0.50,0.23,23-24,Ataque
64,5,Rodrygo,F M,30,1965,6,5,2.47,2.20,4.72,4.00,0.22,0.18,24-25,Ataque
0,1,Kylian Mbappe-Lottin,F,28,2422,24,4,4.91,2.34,23.77,7.03,0.88,0.26,25-26,Ataque

In [111]:
team.loc[team["player"]=="Franco Mastantuono", "linea"] = "Ataque"
team.loc[team["player"]=="Arda Güler", "linea"] = "Medio"
team.loc[team["player"]=="Jude Bellingham", "linea"] = "Medio"
team.loc[team["player"]=="Federico Valverde", "linea"] = "Medio"

In [112]:
team.to_csv("team.csv", index=False)